[cryptoMaterial]
certPath = "conf"   # The certification path

[network]
peers=["127.0.0.1:20200", "127.0.0.1:20201"]    # The peer list to connect

[account]
keyStoreDir = "account"
accountFileFormat = "pem"